title: nocaps
email: rishabhjain@gatech.edu
description: Towards novel object captioning
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://nocaps.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['_pages']
